# This is a basic workflow to help you get started with Actions

name: CI
on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
  workflow_dispatch:


jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      - name: run jmeter on github action
        uses: actions/checkout@v3
